# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "A first hello"
  build_feature:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
     - checkout
          - run: echo "feature branch"
workflows:
  version: 2
  build_and_test_feature:
    jobs:
      - build_feature
        filters:
          branches:
            ignore: master
  build_and_test_master:
    Jobs:
      - build
        filters:
          branches:
            only: master