#env: sandbox
server:
  applicationConnectors:
    - type: http
      port: 12000
      reuseAddress: true
      inputBufferSize: 8KiB
  adminConnectors:
    - type: http
      port: 12001
      reuseAddress: true
      useServerHeader: true
  requestLog:
    appenders:
      - type: file
        timeZone: UTC
        currentLogFilename: /tmp/hello-requests.log
        archive: true
        archivedLogFilenamePattern: /tmp/hello-requests-%d.log.gz
        archivedFileCount: 10